baseURL = 'https://noalerch.github.io/'
languageCode = 'se-sv'
enableEmoji = true
canonifyURLs = true
theme = "hugo-theme-relearn"

[params]
themeVariant = ["relearn-custom", "relearn-light"]
title = 'ForsCaps'
author = "(St)yr"

