baseURL = 'https://noalerch.github.io/'
languageCode = 'se-sv'
enableEmoji = true
canonifyURLs = true
theme = "hugo-theme-relearn"

[params]
themeVariant = ["red", "relearn-custom", "relearn-light"]
title = 'Noa Lerch'
author = "Noa Lerch"

[markup.goldmark.renderer]
    unsafe = true

